import Foundation

// usage: sshot-embed <VERSION file> <vm dir> <output.swift>
let args = CommandLine.arguments
guard args.count == 4 else {
    FileHandle.standardError.write(Data("usage: sshot-embed <version-file> <vm-dir> <output>\n".utf8))
    exit(2)
}
let versionURL = URL(fileURLWithPath: args[1])
let vmURL = URL(fileURLWithPath: args[2]).standardizedFileURL
let outURL = URL(fileURLWithPath: args[3])

let version = try String(contentsOf: versionURL, encoding: .utf8).trimmingCharacters(in: .whitespacesAndNewlines)

var files: [(path: String, mode: Int, base64: String)] = []
let fm = FileManager.default
if let walker = fm.enumerator(at: vmURL, includingPropertiesForKeys: [.isRegularFileKey]) {
    for case let url as URL in walker {
        guard try url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true else { continue }
        let relative = String(url.standardizedFileURL.path.dropFirst(vmURL.path.count + 1))
        let perms = try fm.attributesOfItem(atPath: url.path)[.posixPermissions] as? Int ?? 0o644
        files.append((relative, perms & 0o111 != 0 ? 0o755 : 0o644, try Data(contentsOf: url).base64EncodedString()))
    }
}
files.sort { $0.path < $1.path }

var out = """
// Generated by sshot-embed from VERSION and vm/. Do not edit.

extension Payload {
    static let version = \(version.debugDescription)
    static let files: [File] = [

"""
for file in files {
    out += "        File(path: \(file.path.debugDescription), mode: 0o\(String(file.mode, radix: 8)), base64: \(file.base64.debugDescription)),\n"
}
out += "    ]\n}\n"

try out.write(to: outURL, atomically: true, encoding: .utf8)
